language: python
python: 2.7

before_install:
  - export GALAXY_REPO=https://github.com/galaxyproject/galaxy
  - export GALAXY_RELEASE=release_17.01
  - export PLANEMO_CONDA_PREFIX="$HOME/conda"
  - unset JAVA_HOME

install:
  - pip install flake8 flake8-import-order planemo==0.39
  - planemo conda_init
  - export PATH="$PLANEMO_CONDA_PREFIX/bin:$PATH"
  - conda create -y -q -c bioconda --name iuc_conda samtools=0.1.19 bcftools
  - . activate iuc_conda
  - planemo --version
  - conda --version

script:
  - set -e
  - planemo conda_install tools/multiqc/
  - planemo test --conda_dependency_resolution --galaxy_branch "$GALAXY_RELEASE" --galaxy_source "$GALAXY_REPO" tools/multiqc/
